window.esdocSearchIndex = [
  [
    "web-cell-cli/source/component.js~component",
    "class/source/Component.js~Component.html",
    "<span>Component</span> <span class=\"search-result-import-path\">web-cell-cli/source/Component.js</span>",
    "class"
  ],
  [
    "web-cell-cli/source/utility.js~addcomponent",
    "function/index.html#static-function-addComponent",
    "<span>addComponent</span> <span class=\"search-result-import-path\">web-cell-cli/source/utility.js</span>",
    "function"
  ],
  [
    "web-cell-cli/source/command.js~bundle",
    "function/index.html#static-function-bundle",
    "<span>bundle</span> <span class=\"search-result-import-path\">web-cell-cli/source/command.js</span>",
    "function"
  ],
  [
    "web-cell-cli/source/command.js~createcell",
    "function/index.html#static-function-createCell",
    "<span>createCell</span> <span class=\"search-result-import-path\">web-cell-cli/source/command.js</span>",
    "function"
  ],
  [
    "web-cell-cli/source/command.js~createrouter",
    "function/index.html#static-function-createRouter",
    "<span>createRouter</span> <span class=\"search-result-import-path\">web-cell-cli/source/command.js</span>",
    "function"
  ],
  [
    "web-cell-cli/source/utility.js~folderof",
    "variable/index.html#static-variable-folderOf",
    "<span>folderOf</span> <span class=\"search-result-import-path\">web-cell-cli/source/utility.js</span>",
    "variable"
  ],
  [
    "web-cell-cli/source/utility.js~identifierof",
    "function/index.html#static-function-identifierOf",
    "<span>identifierOf</span> <span class=\"search-result-import-path\">web-cell-cli/source/utility.js</span>",
    "function"
  ],
  [
    "web-cell-cli/source/utility.js~metaof",
    "variable/index.html#static-variable-metaOf",
    "<span>metaOf</span> <span class=\"search-result-import-path\">web-cell-cli/source/utility.js</span>",
    "variable"
  ],
  [
    "web-cell-cli/source/command.js~pack",
    "function/index.html#static-function-pack",
    "<span>pack</span> <span class=\"search-result-import-path\">web-cell-cli/source/command.js</span>",
    "function"
  ],
  [
    "component source/component.js~component,component",
    "test-file/test/index.js.html#lineNumber15",
    "Core class",
    "test"
  ],
  [
    "component#tohtml source/component.js~component#tohtml,component#tohtml",
    "test-file/test/index.js.html#lineNumber101",
    "Core class Bundle to HTML",
    "test"
  ],
  [
    "component#tojs source/component.js~component#tojs,component#tojs",
    "test-file/test/index.js.html#lineNumber117",
    "Core class Bundle to JS",
    "test"
  ],
  [
    "component.parsecss source/component.js~component.parsecss,component.parsecss",
    "test-file/test/index.js.html#lineNumber22",
    "Core class Parse CSS files",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber49",
    "Core class Parse mixed HTML",
    "test"
  ],
  [
    "component.findstyle component.parsecss source/component.js~component.findstyle,component.findstyle source/component.js~component.parsecss,component.parsecss",
    "test-file/test/index.js.html#lineNumber59",
    "Core class Parse mixed HTML Find & Parse styles",
    "test"
  ],
  [
    "component.packjs source/component.js~component.packjs,component.packjs",
    "test-file/test/index.js.html#lineNumber86",
    "Core class Parse mixed HTML Parse script",
    "test"
  ],
  [
    "component.parsehtml source/component.js~component.parsehtml,component.parsehtml",
    "test-file/test/index.js.html#lineNumber36",
    "Core class Parse pure HTML",
    "test"
  ],
  [
    "",
    "test-file/test/utility.js.html#lineNumber4",
    "Utility methods",
    "test"
  ],
  [
    "identifierof source/component.js~component.identifierof,identifierof",
    "test-file/test/utility.js.html#lineNumber8",
    "Utility methods Tag name to Class name",
    "test"
  ],
  [
    "source/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "source/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "source/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "source/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "source/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "source/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "source/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "source/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "source/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "source/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "source/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "source/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "source/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "source/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "source/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "source/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "source/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "source/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "source/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "source/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "source/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "source/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "source/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "source/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "source/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "source/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "source/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "source/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "source/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "source/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "source/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "source/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "source/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "source/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "source/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "source/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "source/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "source/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "source/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "source/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "source/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "source/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "source/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "source/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "source/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "source/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "source/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "source/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "source/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "source/.external-ecmascript.js~String",
    "external"
  ],
  [
    "source/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "source/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "source/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "source/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "source/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "source/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "source/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "source/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "source/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "source/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "source/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "source/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "source/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "source/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "source/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "source/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "source/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "source/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "source/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "source/.external-ecmascript.js~function",
    "external"
  ],
  [
    "source/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "source/.external-ecmascript.js~null",
    "external"
  ],
  [
    "source/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "source/.external-ecmascript.js~number",
    "external"
  ],
  [
    "source/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "source/.external-ecmascript.js~object",
    "external"
  ],
  [
    "source/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "source/.external-ecmascript.js~string",
    "external"
  ],
  [
    "source/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "source/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "source/.external-webapi.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "source/.external-webapi.js~AudioContext",
    "external"
  ],
  [
    "source/.external-webapi.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "source/.external-webapi.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "source/.external-webapi.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "source/.external-webapi.js~DocumentFragment",
    "external"
  ],
  [
    "source/.external-webapi.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "source/.external-webapi.js~Element",
    "external"
  ],
  [
    "source/.external-webapi.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "source/.external-webapi.js~Event",
    "external"
  ],
  [
    "source/.external-webapi.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "source/.external-webapi.js~Node",
    "external"
  ],
  [
    "source/.external-webapi.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "source/.external-webapi.js~NodeList",
    "external"
  ],
  [
    "source/.external-webapi.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "source/.external-webapi.js~XMLHttpRequest",
    "external"
  ],
  [
    "source/component.js",
    "file/source/Component.js.html",
    "source/Component.js",
    "file"
  ],
  [
    "source/component.js~component#assetof",
    "class/source/Component.js~Component.html#instance-method-assetOf",
    "source/Component.js~Component#assetOf",
    "method"
  ],
  [
    "source/component.js~component#constructor",
    "class/source/Component.js~Component.html#instance-constructor-constructor",
    "source/Component.js~Component#constructor",
    "method"
  ],
  [
    "source/component.js~component#entry",
    "class/source/Component.js~Component.html#instance-member-entry",
    "source/Component.js~Component#entry",
    "member"
  ],
  [
    "source/component.js~component#name",
    "class/source/Component.js~Component.html#instance-member-name",
    "source/Component.js~Component#name",
    "member"
  ],
  [
    "source/component.js~component#path",
    "class/source/Component.js~Component.html#instance-member-path",
    "source/Component.js~Component#path",
    "member"
  ],
  [
    "source/component.js~component#tohtml",
    "class/source/Component.js~Component.html#instance-method-toHTML",
    "source/Component.js~Component#toHTML",
    "method"
  ],
  [
    "source/component.js~component#tojs",
    "class/source/Component.js~Component.html#instance-method-toJS",
    "source/Component.js~Component#toJS",
    "method"
  ],
  [
    "source/component.js~component.findstyle",
    "class/source/Component.js~Component.html#static-method-findStyle",
    "source/Component.js~Component.findStyle",
    "method"
  ],
  [
    "source/component.js~component.identifierof",
    "class/source/Component.js~Component.html#static-method-identifierOf",
    "source/Component.js~Component.identifierOf",
    "method"
  ],
  [
    "source/component.js~component.packjs",
    "class/source/Component.js~Component.html#static-method-packJS",
    "source/Component.js~Component.packJS",
    "method"
  ],
  [
    "source/component.js~component.parsecss",
    "class/source/Component.js~Component.html#static-method-parseCSS",
    "source/Component.js~Component.parseCSS",
    "method"
  ],
  [
    "source/component.js~component.parsehtml",
    "class/source/Component.js~Component.html#static-method-parseHTML",
    "source/Component.js~Component.parseHTML",
    "method"
  ],
  [
    "source/command.js",
    "file/source/command.js.html",
    "source/command.js",
    "file"
  ],
  [
    "source/index.js",
    "file/source/index.js.html",
    "source/index.js",
    "file"
  ],
  [
    "source/install.js",
    "file/source/install.js.html",
    "source/install.js",
    "file"
  ],
  [
    "source/parser.js",
    "file/source/parser.js.html",
    "source/parser.js",
    "file"
  ],
  [
    "source/template.js",
    "file/source/template.js.html",
    "source/template.js",
    "file"
  ],
  [
    "source/utility.js",
    "file/source/utility.js.html",
    "source/utility.js",
    "file"
  ],
  [
    "test/example-html/index.js",
    "test-file/test/example-html/index.js.html",
    "test/example-html/index.js",
    "testFile"
  ],
  [
    "test/example-js/index.js",
    "test-file/test/example-js/index.js.html",
    "test/example-js/index.js",
    "testFile"
  ],
  [
    "test/index.js",
    "test-file/test/index.js.html",
    "test/index.js",
    "testFile"
  ],
  [
    "test/utility.js",
    "test-file/test/utility.js.html",
    "test/utility.js",
    "testFile"
  ]
]